### ISSUE TITLE
Whats the use of Litespeed and how does it compare to Vue.js?

### ISSUE THREAD

**Issue by novidtech** [litespeed-js/litespeed.js#5]
Hi, I'm new to this, Whats the use of Litespeed and how does it compare to Vue.js? How do I find out more on this project and should I try it?

**Comment by eldadfux** [comment]
Hey @novidtech , this project is currently developed completely under the hood.

We're building a vanilla JS framework that aims to be super simple to use, and don't require the crazy dependency tree of modern JS frameworks. We're still working on making this available for widespread use. Currently in use for https://github.com/appwrite/appwrite console dashboard.

**Comment by novidtech** [comment]
Oh, wow. That's great. I love appwrite. I can't wait to see where this
framework goes.

Kind regards,

Rohan Groombridge
Novidtech | Director
E: Rohan.Groombridge@Novidtech.com.au
M: 0409860838

**Comment by novidtech** [comment]
I am using angular for drabble functionality, can I use Litespeed for this?

Kind regards,

Rohan Groombridge
Novidtech | Director
E: Rohan.Groombridge@Novidtech.com.au
M: 0409860838

**Comment by eldadfux** [comment]
Probably wait a bit for us to fill it's more stable 😉

**Comment by novidtech** [comment]
Ah ok. Thanks. Will do.


Kind regards,

Rohan Groombridge
Novidtech | Director
E: Rohan.Groombridge@Novidtech.com.au
M: 0409860838
